name: Build Flash-UI Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Project Dependencies
        run: npm install

      - name: Build Vite Project
        run: npm run build

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project
        run: |
          cordova create my-app com.flashui.app "Flash-UI"
          cd my-app
          cordova platform add android

      - name: Copy Vite Build Files to Cordova
        run: |
          rm -rf my-app/www/*
          cp -r dist/* my-app/www/

      - name: Build Android APK
        run: |
          cd my-app
          cordova build android --bundle

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Flash-UI-apk
          path: my-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
